spring:
  application:
    name: multi-mcp-server
  ai:
    mcp:
      server:
        capabilities:
          tool: true
        annotation-scanner:
          enabled: true
        type: sync
        enabled: false
server:
  port: 8080

